apiVersion: v1
kind: Service
metadata:
  name: {{ include "trishul.fullname" . }}-frontend
  labels:
    {{- include "trishul.frontend.labels" . | nindent 4 }}
  {{- with .Values.service.frontend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
  - port: {{ .Values.service.frontend.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.service.frontend.type "NodePort") .Values.service.frontend.nodePort }}
    nodePort: {{ .Values.service.frontend.nodePort }}
    {{- end }}
  selector:
    {{- include "trishul.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
