{{- if and .Values.monitoring.enabled .Values.monitoring.grafana.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trishul.fullname" . }}-grafana-datasources
  labels:
    {{- include "trishul.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://{{ include "trishul.fullname" . }}-prometheus:9090
      isDefault: true
      editable: false
      jsonData:
        timeInterval: 30s

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trishul.fullname" . }}-grafana-dashboards-config
  labels:
    {{- include "trishul.labels" . | nindent 4 }}
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: 'Trishul'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 30
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trishul.fullname" . }}-grafana-data
  labels:
    {{- include "trishul.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.monitoring.grafana.storage.storageClass }}
  storageClassName: {{ .Values.monitoring.grafana.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.monitoring.grafana.storage.size }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trishul.fullname" . }}-grafana
  labels:
    {{- include "trishul.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "trishul.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "trishul.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
        runAsNonRoot: true
      containers:
      - name: grafana
        image: grafana/grafana:10.2.3
        ports:
        - name: web
          containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: {{ .Values.monitoring.grafana.adminUser }}
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.monitoring.grafana.adminPassword }}
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_SERVER_ROOT_URL
          value: "http://localhost:{{ .Values.monitoring.grafana.service.nodePort }}"
        - name: GF_ANALYTICS_REPORTING_ENABLED
          value: "false"
        - name: GF_ANALYTICS_CHECK_FOR_UPDATES
          value: "false"
        - name: GF_INSTALL_PLUGINS
          value: ""
        volumeMounts:
        - name: data
          mountPath: /var/lib/grafana
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: dashboards-config
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboards
          mountPath: /var/lib/grafana/dashboards
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.monitoring.grafana.resources | nindent 10 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "trishul.fullname" . }}-grafana-data
      - name: datasources
        configMap:
          name: {{ include "trishul.fullname" . }}-grafana-datasources
      - name: dashboards-config
        configMap:
          name: {{ include "trishul.fullname" . }}-grafana-dashboards-config
      - name: dashboards
        configMap:
          name: {{ include "trishul.fullname" . }}-grafana-dashboards

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trishul.fullname" . }}-grafana
  labels:
    {{- include "trishul.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.monitoring.grafana.service.type }}
  {{- if eq .Values.monitoring.grafana.service.type "NodePort" }}
  ports:
  - name: web
    port: 3000
    targetPort: 3000
    nodePort: {{ .Values.monitoring.grafana.service.nodePort }}
    protocol: TCP
  {{- else }}
  ports:
  - name: web
    port: 3000
    targetPort: 3000
    protocol: TCP
  {{- end }}
  selector:
    {{- include "trishul.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}
